# Generated by Django 4.1 on 2022-08-13 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_restaurant_place_remove_waiter_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharr', models.CharField(max_length=40)),
                ('namee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
