# Generated by Django 4.0 on 2021-12-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honeybadger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honeyname', models.CharField(max_length=10)),
                ('behaviour', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sankename', models.CharField(max_length=9)),
                ('colourname', models.CharField(max_length=10)),
                ('beahviour', models.CharField(max_length=15)),
            ],
        ),
    ]
