# Generated by Django 4.0 on 2021-12-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Honeybadger',
        ),
        migrations.RenameField(
            model_name='snake',
            old_name='sankename',
            new_name='cobname',
        ),
    ]
